
spring:
  profiles:
    active: druid

  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss


  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB


mybatis:
  type-aliases-package: com.panda.**.domin
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.panda: trace
    org.springframework: warn

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8181
